### ISSUE TITLE
add a 404 page if not route url  not found 

### ISSUE THREAD

**Issue by Kunalbhandari** [Kunalbhandari/portfolio#10]

**Comment by jsvigneshkanna** [comment]
Assign me this issue, will implement this new page

**Comment by nikhil-7span** [comment]
@Kunalbhandari Can you please assign me above issue. I will do that.

Thanks!

**Comment by Kunalbhandari** [comment]
please feel free to open a PR, will review and merge it @jsvigneshkanna  @nikhil-7span
